#[derive(thiserror::Error, Debug)]
pub enum Error {
	#[error("ParseError")]
	ParseError,
	#[error("KeyLengthIsInvalid")]
	KeyLengthIsInvalid,
	#[error("PublicKeyIsInvalid")]
	PublicKeyIsInvalid,
	#[error("RsaSignatureIsInvalid")]
	RsaSignatureIsInvalid,
	#[error("DerEncodingError")]
	DerEncodingError,
	#[error("UnknownMREnclave")]
	UnknownMREnclave,
	#[error("UnknownMRSigner")]
	UnknownMRSigner,
	#[error("UnsupportedDCAPQuoteVersion")]
	UnsupportedDCAPQuoteVersion,
	#[error("UnsupportedDCAPAttestationKeyType")]
	UnsupportedDCAPAttestationKeyType,
	#[error("UnsupportedQuoteAuthData")]
	UnsupportedQuoteAuthData,
	#[error("UnsupportedDCAPPckCertFormat")]
	UnsupportedDCAPPckCertFormat,
	#[error("EnclaveRejectedByQE")]
	EnclaveRejectedByQE,
	#[error("LeafCertificateParsingError")]
	LeafCertificateParsingError,
	#[error("IntermediateCertificateParsingError")]
	IntermediateCertificateParsingError,
	#[error("CertificateChainIsInvalid")]
	CertificateChainIsInvalid,
	#[error("CertificateChainIsTooShort")]
	CertificateChainIsTooShort,
	#[error("IntelExtensionCertificateDecodingError")]
	IntelExtensionCertificateDecodingError,
	#[error("IntelExtensionAmbiguity")]
	IntelExtensionAmbiguity,
	#[error("FmspcOidIsMissing")]
	FmspcOidIsMissing,
	#[error("FmspcLengthMismatch")]
	FmspcLengthMismatch,
	#[error("FmspcDecodingError")]
	FmspcDecodingError,
	#[error("CpuSvnOidIsMissing")]
	CpuSvnOidIsMissing,
	#[error("CpuSvnLengthMismatch")]
	CpuSvnLengthMismatch,
	#[error("CpuSvnDecodingError")]
	CpuSvnDecodingError,
	#[error("PceSvnOidIsMissing")]
	PceSvnOidIsMissing,
	#[error("PceSvnDecodingError")]
	PceSvnDecodingError,
	#[error("PceSvnLengthMismatch")]
	PceSvnLengthMismatch,
	#[error("QEReportHashMismatch")]
	QEReportHashMismatch,
	#[error("IsvEnclaveReportSignatureIsInvalid")]
	IsvEnclaveReportSignatureIsInvalid,
}
